version: '3.6'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - conerf_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - conerf_network

  web:
    build: docker/back
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: uwsgi --ini uwsgi.ini
    tty: true
    volumes:
      - ./back/django:/app
      - ${MNT}:/mnt
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - conerf_network

  nextjs:
    build: docker/front
    # command: yarn run dev
    tty: true
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    depends_on:
      - web
    networks:
      - conerf_network

networks:
  conerf_network:

volumes:
  conerf_postgres:
