version: '3.6'

services:
  flask:
    build: docker/back
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0
