# Generated by Django 4.2.7 on 2023-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='select_job',
            field=models.BooleanField(default=False),
        ),
    ]
