# Generated by Django 4.2 on 2023-11-11 14:31

import conerf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0002_job_select_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='thumbnail',
            field=models.CharField(default='static/images/noimage.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='movies_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=conerf.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conerf.job')),
            ],
        ),
    ]
