# Generated by Django 4.2 on 2023-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0003_job_thumbnail_alter_job_movies_url_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
