# Generated by Django 4.2 on 2023-11-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0004_job_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='thumbnail',
            field=models.CharField(blank=True, default='static/images/noimage.png', max_length=200),
        ),
    ]
