# Generated by Django 4.2.7 on 2023-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
