# Generated by Django 4.2.7 on 2023-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0007_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_movie',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1', 'Upload Movies'), ('2', 'Run ffmpeg'), ('3', 'Finished ffmpeg'), ('4', 'Run colmap'), ('5', 'Finished colmap'), ('6', 'Run train'), ('7', 'Finished train')], default='1', max_length=2),
        ),
    ]
