# Generated by Django 4.2.7 on 2023-12-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conerf', '0008_job_output_movie_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='trained_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
